workspace:
  base: /go
  path: src/github.com/SohoHouse/drone-helm

pipeline:
  test:
    image: golang:1.8
    commands:
      - go get
      - go test -cover -coverprofile=coverage.out

  compile:
    image: golang:1.8
    commands:
      - export PATH=$PATH:/go/bin
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo


  build_docker_image:
    image: plugins/docker
    repo: quay.io/sohohouse/drone-helm
    registry: quay.io
    storage_path: /drone/docker
    storage_driver: overlay
    email: "info@info.com"
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    secrets:
      - docker_username
      - docker_password
      
  slack:
    image: plugins/slack
    channel: deploys
    username: drone
    template: >
      {{ build.author }} finished building  *<http://build.staging.sohohousedigital.com/SohoHouse/{{ repo.name }}/{{ build.number }}|{{ build.branch }} ({{ build.number }})>* of {{ repo.name }}  with a {{ build.status }} status
    secrets: [slack_webhook]
    

plugin:
  name: drone-helm
  desc: Execute helm to
  type: deploy
  image: quay.io/sohohouse/drone-helm
  labels:
    - deploy
    - kubernetes
    - helm
